/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_H
#define server_H

#include <thrift/TDispatchProcessor.h>
#include "webserver_types.h"

namespace serverns {

class serverIf {
 public:
  virtual ~serverIf() {}
  virtual void getHtml(std::string& _return, const std::string& url) = 0;
};

class serverIfFactory {
 public:
  typedef serverIf Handler;

  virtual ~serverIfFactory() {}

  virtual serverIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(serverIf* /* handler */) = 0;
};

class serverIfSingletonFactory : virtual public serverIfFactory {
 public:
  serverIfSingletonFactory(const boost::shared_ptr<serverIf>& iface) : iface_(iface) {}
  virtual ~serverIfSingletonFactory() {}

  virtual serverIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(serverIf* /* handler */) {}

 protected:
  boost::shared_ptr<serverIf> iface_;
};

class serverNull : virtual public serverIf {
 public:
  virtual ~serverNull() {}
  void getHtml(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _server_getHtml_args__isset {
  _server_getHtml_args__isset() : url(false) {}
  bool url;
} _server_getHtml_args__isset;

class server_getHtml_args {
 public:

  server_getHtml_args() : url() {
  }

  virtual ~server_getHtml_args() throw() {}

  std::string url;

  _server_getHtml_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const server_getHtml_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const server_getHtml_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const server_getHtml_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class server_getHtml_pargs {
 public:


  virtual ~server_getHtml_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _server_getHtml_result__isset {
  _server_getHtml_result__isset() : success(false) {}
  bool success;
} _server_getHtml_result__isset;

class server_getHtml_result {
 public:

  server_getHtml_result() : success() {
  }

  virtual ~server_getHtml_result() throw() {}

  std::string success;

  _server_getHtml_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const server_getHtml_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const server_getHtml_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const server_getHtml_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _server_getHtml_presult__isset {
  _server_getHtml_presult__isset() : success(false) {}
  bool success;
} _server_getHtml_presult__isset;

class server_getHtml_presult {
 public:


  virtual ~server_getHtml_presult() throw() {}

  std::string* success;

  _server_getHtml_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class serverClient : virtual public serverIf {
 public:
  serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getHtml(std::string& _return, const std::string& url);
  void send_getHtml(const std::string& url);
  void recv_getHtml(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class serverProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<serverIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (serverProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getHtml(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  serverProcessor(boost::shared_ptr<serverIf> iface) :
    iface_(iface) {
    processMap_["getHtml"] = &serverProcessor::process_getHtml;
  }

  virtual ~serverProcessor() {}
};

class serverProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  serverProcessorFactory(const ::boost::shared_ptr< serverIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< serverIfFactory > handlerFactory_;
};

class serverMultiface : virtual public serverIf {
 public:
  serverMultiface(std::vector<boost::shared_ptr<serverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~serverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<serverIf> > ifaces_;
  serverMultiface() {}
  void add(boost::shared_ptr<serverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getHtml(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getHtml(_return, url);
    }
    ifaces_[i]->getHtml(_return, url);
    return;
  }

};

} // namespace

#endif
