// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "server.h"
extern "C" {
  #include "webcurl.h"
}
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <string.h>
#include "lrucache.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::serverns;

class serverHandler : virtual public serverIf {
 public:
  serverHandler() {
    // Your initialization goes here
  }

  void getHtml(std::string& _return) {
    // Your implementation goes here
    std::string body(getWebPage());
    _return.assign(body);
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<serverHandler> handler(new serverHandler());
  shared_ptr<TProcessor> processor(new serverProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  hash_map<int, int> map;

  map[9]= 999;
  cout << map[9] << endl;
  cout << map[10] << endl;
  LRUCache<int, string> lru_cache(100);
  lru_cache.Put(1, "one");
  cout << lru_cache.Get(1) << endl;

  if(lru_cache.Get(2) == "")
    lru_cache.Put(2, "two");
  cout << lru_cache.Get(2);

  return 0;
}

