/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "webserver_constants.h"

namespace serverns {

const webserverConstants g_webserver_constants;

webserverConstants::webserverConstants() {
}

} // namespace

