/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef webserver_CONSTANTS_H
#define webserver_CONSTANTS_H

#include "webserver_types.h"

namespace serverns {

class webserverConstants {
 public:
  webserverConstants();

};

extern const webserverConstants g_webserver_constants;

} // namespace

#endif
